apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: route.openshift.io/v1 
kind: Route 
metadata: 
  name: nginx-route 
spec: 
  path: /
  to: 
    kind: Service 
    name: nginx-service 
  Port:
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.hub.docker.com/viggyvijay/itsvignesh.tech
          tag: latest
          ports:
            - containerPort: 80
