version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t your-dockerhub-username/my-nginx-website:$CIRCLE_BUILD_NUM .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push viggyvijay/itsvignesh.tech:$CIRCLE_BUILD_NUM

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Login to OpenShift
          command: oc login --token=sha256~q6cQgl4FhO0oYFTyhDKAbc1JrIV55AB08Dl7ycpFGBw --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
      - run:
          name: Deploy to OpenShift
          command: oc apply -f your-openshift-deployment.yaml -n vignesh8458-dev

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
