version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
           
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t viggyvijay/itsvignesh.tech:$TAG .
      - run:
          name: Push Docker Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push viggyvijay/itsvignesh.tech:$TAG
      - run:
          name: Login to OpenShift
          command: |
             wget https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-07-14-153706-ga/openshift-client-linux-4.5.0-0.okd-2020-07-14-153706-ga.tar.gz
             tar -xvf openshift-client-linux-4.5.0-0.okd-2020-07-14-153706-ga.tar.gz
             sudo mv oc kubectl /usr/local/bin/
             oc version
             oc login --token=sha256~q6cQgl4FhO0oYFTyhDKAbc1JrIV55AB08Dl7ycpFGBw --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
      - run:
          name: Deploy to OpenShift cloud
          command: oc apply -f your-openshift-deployment.yaml -n vignesh8458-dev

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Login to OpenShift
          command: oc login --token=sha256~q6cQgl4FhO0oYFTyhDKAbc1JrIV55AB08Dl7ycpFGBw --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
      - run:
          name: Deploy to OpenShift cloud
          command: oc apply -f kubernetes-deloyment.yaml -n vignesh8458-dev

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
