version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t your-dockerhub-username/my-nginx-website .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push your-dockerhub-username/my-nginx-website

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Login to OpenShift
          command: oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN
      - run:
          name: Deploy to OpenShift
          command: oc apply -f your-openshift-deployment.yaml

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
